Repository Hintzelab/MABE, pull requests merged in 2018-11, with the labels that each got.

#278 updated mq and mq_conditions to slurm
  pythonTools/mq.py
  pythonTools/mq_conditions.txt
Labels: PR +Needs Testing, PR needs changes

#286 added R measure in python
  Analyze/neurocorrelates.py
Labels: PR Passing Tests

#288 hot fix to address quotes on strings. Quotes were not be added in all…
  Brain/MarkovBrain/MarkovBrain.cpp
  Genome/CircularGenome/CircularGenome.cpp
  Genome/MultiGenome/Chromosome/TemplatedChromosome.cpp
  Genome/MultiGenome/MultiGenome.cpp
  Utilities/Data.cpp
  Utilities/Data.h
Labels: PR approved
