Repository Hintzelab/MABE, pull requests merged in 2018-04, with the labels that each got.

#176 Feature update simple optimizer
  Optimizer/SimpleOptimizer/SimpleOptimizer.cpp
  Optimizer/SimpleOptimizer/SimpleOptimizer.h
Labels: approved

#180 Rewrite
  Global.cpp
  Utilities/Loader.cpp
  Utilities/Parameters.cpp
Labels: changes need review

#184 pyreq now always install modules into user dir (--user)
  pythonTools/utils/pyreq.py
Labels: approved

#186 isnan -> std::isnan, isinf -> std::isinf, to resolve macos compile pr…
  World/XorWorld/XorWorld.cpp
Labels: approved

#193 Deprecate old world and organism functions
  Organism/Organism.cpp
  Organism/Organism.h
  World/AbstractWorld.h
  World/TestWorld/TestWorld.h
  World/XorWorld/XorWorld.cpp
  World/XorWorld/XorWorld.h
Labels: PR approved

#192 Hotfix fix simple optimizer cull below
  Optimizer/SimpleOptimizer/SimpleOptimizer.cpp
Labels: PR approved

#196 updated .gitignore
  .gitignore
Labels: PR approved

#205 fixed namespace closing. Also cause exit(1) on dirty Parameters file
  Utilities/Parameters.cpp
Labels: PR needs review

#197 upgrading to c++14
  pythonTools/mbuild.py
Labels: PR approved

#199 Feature island optimizer
  Optimizer/IslandsOptimizer/IslandsOptimizer.cpp
  Optimizer/IslandsOptimizer/IslandsOptimizer.h
  buildOptions.txt
Labels: PR approved

#206 Patch command line misread
  Utilities/Parameters.cpp
  Utilities/Parameters.h
  main.cpp
Labels: PR approved, question
